#!/bin/bash

verbose=''

while (( $# > 0 )); do
    arg="$1"
    shift
    case $arg in
    -v)
        verbose='-v'
	;;
    esac
done

if [ ! -d out/Default ]; then
    echo >&2 'error: run configure before build'
    exit 1
fi

if uname -a | grep -q 'MINGW'; then
    suffix='.exe'
fi

time support/bin/ninja$suffix -C out/Default all -j6 $verbose
